
<Project Sdk="Microsoft.NET.Sdk">


	
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\Debug\netstandard2.0\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="bin\Debug\netstandard2.0\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="bin\Debug\netstandard2.0\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Bobbing.cs" />
    <Compile Remove="Items\PlagueCombo.cs" />
    <Compile Remove="Items\TwoSidedDie - BuffAlt.cs" />
    <Compile Remove="Items\TwoSidedDie - DisplayAlt.cs" />
    <Compile Remove="Items\TwoSidedDie OLD.cs" />
    <Compile Remove="PlagueMask.cs" />
    <Compile Remove="Utilities\ShellStackTracker.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="SupplyDropSounds.bnk" />
    <None Remove="supplydrop_assets" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SupplyDropSounds.bnk" />
    <EmbeddedResource Include="supplydrop_assets" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="BepInEx.Analyzers" Version="1.0.*">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="BepInEx.Core" Version="5.4.21" />
	  <PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.0-r.0" />
	  <PackageReference Include="UnityEngine.Modules" Version="2021.3.33">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="MMHOOK.RoR2" Version="2025.11.19">
		  <NoWarn>NU1701</NoWarn>
	  </PackageReference>
	  <PackageReference Include="R2API" Version="5.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AK.Wwise.Unity.API">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Managed\AK.Wwise.Unity.API.dll</HintPath>
    </Reference>
    <Reference Include="ItemStats">
      <HintPath>..\..\..\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\PostStorm\BepInEx\plugins\Moffein-ItemStats\ItemStats.dll</HintPath>
    </Reference>
    <Reference Include="LookingGlass">
      <HintPath>..\..\..\AppData\Roaming\r2modmanPlus-local\RiskOfRain2\profiles\PostStorm\BepInEx\plugins\DropPod-LookingGlass\LookingGlass\LookingGlass.dll</HintPath>
    </Reference>
    <Reference Include="RoR2">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Managed\RoR2.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\netstandard2.1\" />
  </ItemGroup>

</Project>
